/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Dany0
 */
public class ConsultaVenta extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaVenta
     */
    public ConsultaVenta() {
        initComponents();
        num(txtNumeroVenta);
    }
    private void num(JTextField a){
       a.addKeyListener(new KeyAdapter(){
           @Override
           public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if(!Character.isDigit(c)){
                    e.consume();
            
                }
               
                
           }
       });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNumeroVenta = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArticulos = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 21, 126), 3));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Numero de venta: ");

        txtNumeroVenta.setBorder(null);
        txtNumeroVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroVentaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroVentaKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cliente:");

        lblCliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblCliente.setText("-  -  -  -  -  -  -  -");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Articulos:");

        txtArticulos.setColumns(20);
        txtArticulos.setRows(5);
        jScrollPane1.setViewportView(txtArticulos);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Monto total: ");

        lblMonto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(0, 0, 0));
        lblMonto.setText("-  -  -  -  -  -  -");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fecha de compra:");

        lblFecha.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("-  -  -  -  -  -  -  -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(txtNumeroVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMonto)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(lblFecha)
                        .addGap(321, 321, 321))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumeroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCliente)
                    .addComponent(jLabel7)
                    .addComponent(lblFecha))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblMonto))
                .addGap(146, 146, 146))
        );
    }// </editor-fold>//GEN-END:initComponents
    /*Ruta yu credenciales de la base de datos en el localhost*/
    String url = "jdbc:mysql://localhost:3306/tienda";
    String username = "root";
    String password = "";
    String nombreUsuario;
    String driver = "com.mysql.jdbc.Connection";
    PreparedStatement pstm;
    ResultSet rs;
    private void txtNumeroVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroVentaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroVentaKeyReleased

    ///Metodo que se ejecuta al presionar la tecla ENTER consultando a la base de datos si existe el numero de venta y obteniendo los datos solicitados
    private void txtNumeroVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroVentaKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            if(txtNumeroVenta.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Ingrese un numero de venta.", "Error de entrada de informacion", JOptionPane.ERROR_MESSAGE);
            }else{
                int numeroCompra = Integer.parseInt(txtNumeroVenta.getText());
            try{
             Connection connection = (com.mysql.jdbc.Connection)DriverManager.getConnection(url, username, password);
                pstm = connection.prepareStatement("Select * from estaventa where numeroCompra = ?");
                pstm.setInt(1, numeroCompra);
                rs = pstm.executeQuery();
                if(rs.next()){
                    lblCliente.setText(rs.getString("nombreCliente"));
                    txtArticulos.setText(rs.getString("articulos"));
                    lblFecha.setText(rs.getString("fecha"));
                    lblMonto.setText("$ " +String.valueOf(rs.getDouble("total")));
                    connection.close();
                }else{
                    JOptionPane.showMessageDialog(null, "El numero de venta ingresado no existe en la base de datos, asegurese de la validez del mismo", "Numero de venta invalido.", JOptionPane.ERROR_MESSAGE);
                    txtNumeroVenta.setText("");
                }
                
                
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error al consultar en la base de datos.", "Error de conexion", JOptionPane.ERROR_MESSAGE);
            }
        }
            }
        
            
    }//GEN-LAST:event_txtNumeroVentaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JTextArea txtArticulos;
    private javax.swing.JTextField txtNumeroVenta;
    // End of variables declaration//GEN-END:variables
}
