/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.event.KeyAdapter;
import java.time.LocalDate;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dany0
 */
public class IngresoVenta extends javax.swing.JPanel {

    /**
     * Creates new form IngresoVenta
     */
    public IngresoVenta() {
        initComponents();
        txtCodProducto.setEditable(false);
        notnum(txtNombreCliente);
    }
    private void notnum(JTextField a){
       a.addKeyListener(new KeyAdapter(){
           public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if(Character.isDigit(c) && c != '.'){
                    e.consume();
            
                }
                if(c == '.' && a.getText().contains(".")){
                    e.consume();
                }
                
           }
       });
    }
    public void LimpiarCajaTexto(){
        txtCodProducto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        btnFacturar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCompra = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 21, 126), 3));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Nombre del cliente:");

        txtNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.setBorder(null);
        txtNombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreClienteKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Codigo de producto:");

        txtCodProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtCodProducto.setBorder(null);
        txtCodProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodProductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodProductoKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Total a pagar:   $");

        lblTotal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("-  -  -  -");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("SubTotal:   $");

        lblSubTotal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblSubTotal.setText("-  -  -  -");

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Descuento:   $");

        lblDescuento.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblDescuento.setForeground(new java.awt.Color(0, 0, 0));
        lblDescuento.setText("-  -  -  -");

        btnFacturar.setBackground(new java.awt.Color(255, 255, 255));
        btnFacturar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 21, 126), 2, true));
        btnFacturar.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFacturar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturarMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Generar factura");

        javax.swing.GroupLayout btnFacturarLayout = new javax.swing.GroupLayout(btnFacturar);
        btnFacturar.setLayout(btnFacturarLayout);
        btnFacturarLayout.setHorizontalGroup(
            btnFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFacturarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        btnFacturarLayout.setVerticalGroup(
            btnFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFacturarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio unitario (USD)", "Descuento (USD)"
            }
        ));
        jScrollPane2.setViewportView(tblCompra);
        if (tblCompra.getColumnModel().getColumnCount() > 0) {
            tblCompra.getColumnModel().getColumn(0).setPreferredWidth(750);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblSubTotal))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDescuento)
                                .addComponent(lblTotal))))
                    .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1224, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblSubTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblDescuento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modelo = new DefaultTableModel();
   String url = "jdbc:mysql://localhost:3306/tienda";
    String username = "root";
    String password = "";
    String nombreUsuario;
    String driver = "com.mysql.jdbc.Connection";
    PreparedStatement pstm;
    ResultSet rs;
    public void LimpiarTabla(){
        for(int i = 0; i< tblCompra.getRowCount(); i++){
            modelo.removeRow(i);
            i = i-1;
        }
    }
    private void txtNombreClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNombreClienteKeyReleased

    private void txtNombreClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(txtNombreCliente.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Debe ingresar el nombre nombre del cliente", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                txtCodProducto.setEditable(true);
                txtNombreCliente.transferFocus();
            }
            
        }
    }//GEN-LAST:event_txtNombreClienteKeyPressed

    private void txtCodProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProductoKeyReleased
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_txtCodProductoKeyReleased

    private void btnFacturarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturarMouseClicked
        // TODO add your handling code here:
        if(txtNombreCliente.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Ingrese el nombre del cliente.", "Error de entrada de informacion", JOptionPane.ERROR_MESSAGE);
        }else{
            if(tblCompra.getRowCount() == 0 && txtCodProducto.getText().equals("")){
                JOptionPane.showMessageDialog(null, "No hay productos cargados.", "Error de entrada de informacion", JOptionPane.ERROR_MESSAGE);
            }else{
                String articulos = "";
                int cantidad = 0;
                String cliente = txtNombreCliente.getText();
                double total = Double.parseDouble(lblTotal.getText());
                for(int i = 0; i<tblCompra.getRowCount();i++){
                    articulos = articulos + tblCompra.getValueAt(i, 0) + " \n";
                    cantidad++;
            
                }
                try{
                Connection connection =(com.mysql.jdbc.Connection)DriverManager.getConnection(url, username, password);
                   pstm = connection.prepareStatement("Insert into estaventa(nombreCliente, articulos, cantidadArticulos, total, fecha) values (?,?,?,?,?)");
                   pstm.setString(1, cliente);
                   pstm.setString(2, articulos);
                   pstm.setInt(3, cantidad);
                   pstm.setDouble(4, total);
                   pstm.setString(5, String.valueOf(LocalDate.now()));
                   pstm.execute();
                   LimpiarTabla();
                   txtNombreCliente.setText("");
                   lblSubTotal.setText("- - - -");
                   lblDescuento.setText("- - - -");
                   lblTotal.setText("- - - -");
                   connection.close();
               }catch(SQLException ex){
                   JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos.", "Error de conexion", JOptionPane.ERROR_MESSAGE);
               }
                   }
               }
        
        
        
    }//GEN-LAST:event_btnFacturarMouseClicked

    private void txtCodProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProductoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String CodProducto = txtCodProducto.getText();
           double total = 0;
           double totalDesc = 0;
           double cant;
            try{
               Connection connection =(com.mysql.jdbc.Connection)DriverManager.getConnection(url, username, password);
                pstm = connection.prepareStatement("Select * from misproductos where CodigoProducto = ?");
                pstm.setString(1,CodProducto);
                rs = pstm.executeQuery();
                
                Object[] miCompra = new Object[3];
                modelo = (DefaultTableModel) tblCompra.getModel();
                if(rs.next()){
                   // while(rs.next()){
                    double desc;
                    miCompra [0] = rs.getString("NombreProducto");
                    miCompra [1] = rs.getDouble("PrecioUnitario");
                    desc = rs.getDouble("Descuento");
                    miCompra[2] = Math.round((rs.getDouble("PrecioUnitario")*(desc/100.0))*100.0)/100.0;
                    cant = rs.getDouble("Existencia");
                    cant = cant - 1;
                    pstm = connection.prepareStatement("Update misProductos set Existencia = ? where CodigoProducto = ?");
                    pstm.setDouble(1, cant);
                    pstm.setString(2, CodProducto);
                    pstm.execute();
                    modelo.addRow(miCompra);
                   
                   // }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Producto no encontrado, asegurese ingresar correctamente el codigo", "Codigo invalido", JOptionPane.ERROR_MESSAGE);
                }
                
                LimpiarCajaTexto();
              
              
               
            }catch(SQLException ex){
                System.out.println(ex);
            }
            
                
             for(int i = 0; i<tblCompra.getRowCount(); i++){
                  total = total + (double) tblCompra.getValueAt(i, 1);
                  totalDesc = totalDesc + (double) tblCompra.getValueAt(i, 2);
                 
             }   
              
           total =  Math.round(total*100.0)/100.0;
           totalDesc = Math.round(totalDesc*100.0)/100.0;
           lblSubTotal.setText(String.valueOf(total));
           lblDescuento.setText(String.valueOf(totalDesc));
           lblTotal.setText(String.valueOf(total-totalDesc));
            
        }
    }//GEN-LAST:event_txtCodProductoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnFacturar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCompra;
    private javax.swing.JTextField txtCodProducto;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
