/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author Dany0
 */

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form RegistroVenta
     */
    public Menu() {
       
        initComponents();
       setIconImage(new ImageIcon(getClass().getResource("/Icono.png")).getImage());
        IngresoVenta venta = new IngresoVenta();
        venta.setSize(1150, 580);
        venta.setLocation(0, 0);
        contenido.removeAll();
        contenido.add(venta, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
        
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        btnRegistroVenta = new javax.swing.JPanel();
        lblRegistrarVenta = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JPanel();
        lblConsultar = new javax.swing.JLabel();
        btnIngresarProducto = new javax.swing.JPanel();
        lblIngresarProducto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblIngresarUsuario = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblUsuarioMenu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(86, 21, 126));
        jPanelMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 21, 126), 1, true));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistroVenta.setBackground(new java.awt.Color(86, 21, 126));
        btnRegistroVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroVentaMouseClicked(evt);
            }
        });

        lblRegistrarVenta.setBackground(new java.awt.Color(58, 49, 50));
        lblRegistrarVenta.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblRegistrarVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajero-automatico.png"))); // NOI18N
        lblRegistrarVenta.setText("Registrar venta");

        javax.swing.GroupLayout btnRegistroVentaLayout = new javax.swing.GroupLayout(btnRegistroVenta);
        btnRegistroVenta.setLayout(btnRegistroVentaLayout);
        btnRegistroVentaLayout.setHorizontalGroup(
            btnRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistroVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrarVenta)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        btnRegistroVentaLayout.setVerticalGroup(
            btnRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistroVentaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblRegistrarVenta)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanelMenu.add(btnRegistroVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 100));

        btnConsultar.setBackground(new java.awt.Color(86, 21, 126));
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.setPreferredSize(new java.awt.Dimension(200, 76));
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });

        lblConsultar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblConsultar.setForeground(new java.awt.Color(255, 255, 255));
        lblConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscar.png"))); // NOI18N
        lblConsultar.setText("Consulta una venta");

        javax.swing.GroupLayout btnConsultarLayout = new javax.swing.GroupLayout(btnConsultar);
        btnConsultar.setLayout(btnConsultarLayout);
        btnConsultarLayout.setHorizontalGroup(
            btnConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsultar)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        btnConsultarLayout.setVerticalGroup(
            btnConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConsultarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblConsultar)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanelMenu.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, 100));

        btnIngresarProducto.setBackground(new java.awt.Color(86, 21, 126));
        btnIngresarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarProductoMouseClicked(evt);
            }
        });

        lblIngresarProducto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblIngresarProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anadir (1).png"))); // NOI18N
        lblIngresarProducto.setText("Ingresar productos");

        javax.swing.GroupLayout btnIngresarProductoLayout = new javax.swing.GroupLayout(btnIngresarProducto);
        btnIngresarProducto.setLayout(btnIngresarProductoLayout);
        btnIngresarProductoLayout.setHorizontalGroup(
            btnIngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIngresarProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngresarProducto)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        btnIngresarProductoLayout.setVerticalGroup(
            btnIngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnIngresarProductoLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(lblIngresarProducto)
                .addGap(29, 29, 29))
        );

        jPanelMenu.add(btnIngresarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 100));

        jPanel3.setBackground(new java.awt.Color(86, 21, 126));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.setPreferredSize(new java.awt.Dimension(223, 84));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        lblIngresarUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblIngresarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agregar-usuario (1).png"))); // NOI18N
        lblIngresarUsuario.setText("Registrar usuario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngresarUsuario)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblIngresarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanelMenu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 220, 110));

        btnCerrarSesion.setBackground(new java.awt.Color(86, 21, 126));
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jLabel4.setText("Cerrar sesion");

        javax.swing.GroupLayout btnCerrarSesionLayout = new javax.swing.GroupLayout(btnCerrarSesion);
        btnCerrarSesion.setLayout(btnCerrarSesionLayout);
        btnCerrarSesionLayout.setHorizontalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnCerrarSesionLayout.setVerticalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMenu.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jPanel1.add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 580));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(86, 21, 126));
        jLabel2.setText("GAMING STORE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game-center.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 140, 130));

        contenido.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 1150, 580));

        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(86, 21, 126));
        jLabel7.setText("Divertirse es vida!!!");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));

        lblUsuarioMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblUsuarioMenu.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuarioMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioMenu.setText("Administrador");
        jPanel1.add(lblUsuarioMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 80, 120, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verified-user.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 70, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        // TODO add your handling code here:
       ConsultaVenta consulta = new ConsultaVenta();
       consulta.setSize(1150,580);
       consulta.setLocation(0, 0);
       contenido.removeAll();
       contenido.add(consulta, BorderLayout.CENTER);
       contenido.revalidate();
       contenido.repaint();
       
       
    }//GEN-LAST:event_btnConsultarMouseClicked

    private void btnRegistroVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroVentaMouseClicked
        // TODO add your handling code here:
        IngresoVenta venta = new IngresoVenta();
        venta.setSize(1150, 580);
        venta.setLocation(0, 0);
        contenido.removeAll();
        contenido.add(venta, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
  
        
        
       
        
    }//GEN-LAST:event_btnRegistroVentaMouseClicked

    private void btnIngresarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarProductoMouseClicked
        // TODO add your handling code here:
       IngresoProducto producto = new IngresoProducto();
       producto.setSize(1150,580);
       producto.setLocation(0,0);
       
       contenido.removeAll();
       contenido.add(producto, BorderLayout.CENTER);
       contenido.revalidate();
       contenido.repaint();
    
        
    }//GEN-LAST:event_btnIngresarProductoMouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        RegistroUsuario RUsuario = new RegistroUsuario();
        RUsuario.setSize(1150, 580);
        RUsuario.setLocation(0, 0);
        contenido.removeAll();
        contenido.add(RUsuario, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
     
        
    }//GEN-LAST:event_jPanel3MouseClicked

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
           
           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCerrarSesion;
    private javax.swing.JPanel btnConsultar;
    private javax.swing.JPanel btnIngresarProducto;
    private javax.swing.JPanel btnRegistroVenta;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JLabel lblConsultar;
    private javax.swing.JLabel lblIngresarProducto;
    private javax.swing.JLabel lblIngresarUsuario;
    private javax.swing.JLabel lblRegistrarVenta;
    public javax.swing.JLabel lblUsuarioMenu;
    // End of variables declaration//GEN-END:variables
}
